/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.io.File;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.lang.model.SourceVersion;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Sergio Vega
 */
public class Claves extends javax.swing.JFrame {

    /**
     * Creates new form Claves
     */
    public Claves() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.BtnCrearClaves.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BtnCarpetaCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PathClaves = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFieldNombreClavePrivada = new javax.swing.JTextField();
        TFieldNombreClavePublica = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnCrearClaves = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PathArchivo = new javax.swing.JTextField();
        PathArchivoCifrado = new javax.swing.JTextField();
        PathClavePub = new javax.swing.JTextField();
        BtnCarpetaClavePub = new javax.swing.JButton();
        BtnCarpetaCifrar = new javax.swing.JButton();
        BtnCarpetaDestinoCifrado = new javax.swing.JButton();
        BtnCifrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PathArchivoDescifrar = new javax.swing.JTextField();
        PathClavePriv = new javax.swing.JTextField();
        PathArchivoDescifrado = new javax.swing.JTextField();
        BtnBuscarClavePriv = new javax.swing.JButton();
        BtnCarpetaDestinoDescifrado = new javax.swing.JButton();
        BtnBuscarArchivoCifrado = new javax.swing.JButton();
        BtnDescifrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnCarpetaCrear.setText("Buscar...");
        BtnCarpetaCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarpetaCrearActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Clave Pública:");

        PathClaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PathClavesActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Clave Privada:");

        TFieldNombreClavePrivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFieldNombreClavePrivadaActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccione  la carpeta donde desea almacenar las claves:");

        BtnCrearClaves.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCrearClaves.setText("Crear");
        BtnCrearClaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearClavesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFieldNombreClavePrivada)
                                    .addComponent(TFieldNombreClavePublica, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PathClaves, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCarpetaCrear)
                            .addComponent(BtnCrearClaves, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(76, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PathClaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCarpetaCrear))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFieldNombreClavePrivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFieldNombreClavePublica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(BtnCrearClaves, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Crear Claves", jPanel1);

        jLabel4.setText("Seleccione el archivo a cifrar:");

        jLabel5.setText("Seleccione el archivo de Clave  Pública:");

        jLabel6.setText("Seleccione la carpeta donde desea almacenar el archivo cifrado:");

        PathArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PathArchivoActionPerformed(evt);
            }
        });

        BtnCarpetaClavePub.setText("Buscar...");
        BtnCarpetaClavePub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarpetaClavePubActionPerformed(evt);
            }
        });

        BtnCarpetaCifrar.setText("Buscar...");
        BtnCarpetaCifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarpetaCifrarActionPerformed(evt);
            }
        });

        BtnCarpetaDestinoCifrado.setText("Buscar ...");
        BtnCarpetaDestinoCifrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarpetaDestinoCifradoActionPerformed(evt);
            }
        });

        BtnCifrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCifrar.setText("Cifrar");
        BtnCifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCifrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PathClavePub, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PathArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PathArchivoCifrado, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCarpetaClavePub)
                            .addComponent(BtnCarpetaCifrar)
                            .addComponent(BtnCarpetaDestinoCifrado))))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PathArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCarpetaCifrar))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PathClavePub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCarpetaClavePub))
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PathArchivoCifrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCarpetaDestinoCifrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(BtnCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Cifrar", jPanel2);

        jLabel7.setText("Seleccione el archivo a descifrar:");

        jLabel8.setText("Seleccione el archivo de Clave Privada:");

        jLabel9.setText("Seleccione la carpeta donde desea almacenar el archivo descifrado:");

        BtnBuscarClavePriv.setText("Buscar...");
        BtnBuscarClavePriv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarClavePrivActionPerformed(evt);
            }
        });

        BtnCarpetaDestinoDescifrado.setText("Buscar...");
        BtnCarpetaDestinoDescifrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarpetaDestinoDescifradoActionPerformed(evt);
            }
        });

        BtnBuscarArchivoCifrado.setText("Buscar...");
        BtnBuscarArchivoCifrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarArchivoCifradoActionPerformed(evt);
            }
        });

        BtnDescifrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnDescifrar.setText("Descifrar");
        BtnDescifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDescifrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PathClavePriv, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PathArchivoDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BtnBuscarClavePriv)
                                .addComponent(BtnBuscarArchivoCifrado)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(PathArchivoDescifrado, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BtnCarpetaDestinoDescifrado))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnBuscarArchivoCifrado)
                    .addComponent(PathArchivoDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PathClavePriv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarClavePriv))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PathArchivoDescifrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCarpetaDestinoDescifrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(BtnDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Descifrar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCarpetaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarpetaCrearActionPerformed
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        File archivo = file.getSelectedFile();
        if(archivo != null){
        PathClaves.setText(archivo.getAbsolutePath());
            
        }
        if(this.TFieldNombreClavePrivada.getText() == "" && this.TFieldNombreClavePublica.getText() == "")
        {
  
        }
        else
        {
        this.BtnCrearClaves.setVisible(true);
        
        }
        
        
        
    }//GEN-LAST:event_BtnCarpetaCrearActionPerformed

    private void TFieldNombreClavePrivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFieldNombreClavePrivadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFieldNombreClavePrivadaActionPerformed

    private void PathClavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PathClavesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PathClavesActionPerformed

    private void BtnCarpetaClavePubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarpetaClavePubActionPerformed
       
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        File archivo = file.getSelectedFile();
        if(archivo != null){
        PathClavePub.setText(archivo.getAbsolutePath());
            
        }
   
    }//GEN-LAST:event_BtnCarpetaClavePubActionPerformed

    private void PathArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PathArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PathArchivoActionPerformed

    private void BtnCarpetaDestinoDescifradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarpetaDestinoDescifradoActionPerformed
        
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        File archivo = file.getSelectedFile();
        if(archivo != null){
        PathArchivoDescifrado.setText(archivo.getAbsolutePath());
        
        }
  
    }//GEN-LAST:event_BtnCarpetaDestinoDescifradoActionPerformed

    private void BtnBuscarClavePrivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarClavePrivActionPerformed
         JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        File archivo = file.getSelectedFile();
        if(archivo != null){
        PathClavePriv.setText(archivo.getAbsolutePath());
        
        }
        
    }//GEN-LAST:event_BtnBuscarClavePrivActionPerformed

    private void BtnCarpetaCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarpetaCifrarActionPerformed
       
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        File archivo = file.getSelectedFile();
        if(archivo != null){
        PathArchivo.setText(archivo.getAbsolutePath());
        
        }
    }//GEN-LAST:event_BtnCarpetaCifrarActionPerformed

    private void BtnCarpetaDestinoCifradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarpetaDestinoCifradoActionPerformed
        
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        File archivo = file.getSelectedFile();
        if(archivo != null){
        PathArchivoCifrado.setText(archivo.getAbsolutePath());
        
        }
        
        
        
        
    }//GEN-LAST:event_BtnCarpetaDestinoCifradoActionPerformed

    private void BtnBuscarArchivoCifradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarArchivoCifradoActionPerformed
        
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        File archivo = file.getSelectedFile();
        if(archivo != null){
        PathArchivoDescifrar.setText(archivo.getAbsolutePath());
        
        }

    }//GEN-LAST:event_BtnBuscarArchivoCifradoActionPerformed

    private void BtnCrearClavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearClavesActionPerformed
       
        
        
        if(this.TFieldNombreClavePublica.getText().isEmpty() ||  this.TFieldNombreClavePrivada.getText().isEmpty())
            {
               
               JOptionPane.showMessageDialog(null,  "La informacion de las claves está incompleta");

            }
        else
        {
        
              JOptionPane.showMessageDialog(null, "Se han creado las claves correctamente"); 
        
        }
        
 
    }//GEN-LAST:event_BtnCrearClavesActionPerformed

    private void BtnCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCifrarActionPerformed
       
        
         if(this.PathArchivo.getText().isEmpty()  || this.PathClavePub.getText().isEmpty() || this.PathArchivoCifrado.getText().isEmpty())
            {
   
               
               JOptionPane.showMessageDialog(null,  "Por favor, complete la información");
                
            }
        else
        {
                JOptionPane.showMessageDialog(null, "Se han crifrado correctamente");
               
        
        }
        
        
        
    }//GEN-LAST:event_BtnCifrarActionPerformed

    private void BtnDescifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDescifrarActionPerformed
       
        
        if(this.PathArchivoDescifrar.getText().isEmpty()  || this.PathClavePriv.getText().isEmpty() || this.PathArchivoDescifrado.getText().isEmpty())
            {
   
              
               JOptionPane.showMessageDialog(null,  "Por favor, complete la información");
                
            }
        else
        {
                JOptionPane.showMessageDialog(null, "Se han descrifrado correctamente");
               
        
        }
        
        
        
        
    }//GEN-LAST:event_BtnDescifrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Claves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Claves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Claves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Claves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Claves.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Claves.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Claves.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Claves.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                new Claves().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarArchivoCifrado;
    private javax.swing.JButton BtnBuscarClavePriv;
    private javax.swing.JButton BtnCarpetaCifrar;
    private javax.swing.JButton BtnCarpetaClavePub;
    private javax.swing.JButton BtnCarpetaCrear;
    private javax.swing.JButton BtnCarpetaDestinoCifrado;
    private javax.swing.JButton BtnCarpetaDestinoDescifrado;
    private javax.swing.JButton BtnCifrar;
    private javax.swing.JButton BtnCrearClaves;
    private javax.swing.JButton BtnDescifrar;
    private javax.swing.JTextField PathArchivo;
    private javax.swing.JTextField PathArchivoCifrado;
    private javax.swing.JTextField PathArchivoDescifrado;
    private javax.swing.JTextField PathArchivoDescifrar;
    private javax.swing.JTextField PathClavePriv;
    private javax.swing.JTextField PathClavePub;
    private javax.swing.JTextField PathClaves;
    private javax.swing.JTextField TFieldNombreClavePrivada;
    private javax.swing.JTextField TFieldNombreClavePublica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latest();
    }
}
