package com.robin.mu;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class ValoremeElEsfuerzo {

	public static void main(String[] args) {
		//Testing
//		String plainT = "sehaencontradoafaceapplaaplicacindetransformacindefotografasbasadaenlainteligenciaartificialquerecientementesevolviviralporsufiltrodeedadperollegalostitularesporsupolmicapolticadeprivacidadquerecopilalalistadetusamigosdefacebooksinningunaraznelfaceappdefabricacinrusahaexistidodesdelaprimaveradeperosehavistoafectadoporlasredessocialesenlasltimassemanasyaquemillonesdepersonasdescargaronlaaplicacinparavercmoseverancuandoseanmayoresomenoresointercambiengneroslaaplicacintambincontieneunafuncinquepermitealosusuariosdescargaryeditarfotosdesuscuentasdefacebookquesolofuncionacuandounusuariopermitequefaceappaccedaalacuentaderedessocialesatravsdelaopcininiciarsesinconfacebook";
//		String encryptedT = "emusitowalvgpwnxeiqichpgmxyaggoqavizdiakjudunumtpmsgxusznxeynifshgqvysmtfmyakkzkvsexfqsagomtdmixqkvwrzqurfxkemigpbudvjerbwekylutgjsjqmqshvqzbdpksiygwzubhdexqacgvygxbdqooicgpzuknvivdqisgopiqiykdmpgtoxiyspoebnvizganemmaaqwjgomogsqeqafmtscasvglvrdjgomnhtjqnntvooiparxganzekjqflmjalrkhkxicjmsmdrjejqxrjsyqpnnmyfwnxiifiqgtudtnkvkpmfksiuiywwkztnkpzuunkwkyiaswemyhwqoxtbfiypmcwvyavnkhkeknjkgdwadegbtvueiuvcsvghmeuquemiwvgzkhsrjaarsrsmgbjiyaurfsxqabarzqzpsqhumayrkdwfdegbtvueiuvgsqhuvpgrzumawytmnhfgozyhwtkduvligxwfmwamzvgwjqapsvmmzlwhofiexszaaqwwaekhwrzmaqwjgomogsqccrksranhfgoavnuygzlbmraecnjmubmeemzqyhwjgomnhtgokrvegxipmitfiqwvkpmfksiuiywwgfznnwjqtngtiuvvfmiuiekiyuvpgrlmkrtsuw";
//		String encryptedMessage = BreakingVigenere.encrypt(plainT, "MINSEG");
//		String decryptedMessage = BreakingVigenere.decrypt(encryptedMessage, "MINSEG");
//		System.out.printf("\n\nMain:\nEncryptedT:%s%nEncrypted:%s%nPlainT:%s%nPlain:%s%n", encryptedT, encryptedMessage, plainT,decryptedMessage);

		
		String plain = "sehaencontradoafaceapplaaplicacindetransformacindefotografasbasadaenlainteligenciaartificialquerecientementesevolviviralporsufiltrodeedadperollegalostitularesporsupolmicapolticadeprivacidadquerecopilalalistadetusamigosdefacebooksinningunaraznelfaceappdefabricacinrusahaexistidodesdelaprimaveradeperosehavistoafectadoporlasredessocialesenlasltimassemanasyaquemillonesdepersonasdescargaronlaaplicacinparavercmoseverancuandoseanmayoresomenoresointercambiengneroslaaplicacintambincontieneunafuncinquepermitealosusuariosdescargaryeditarfotosdesuscuentasdefacebookquesolofuncionacuandounusuariopermitequefaceappaccedaalacuentaderedessocialesatravsdelaopcininiciarsesinconfacebook";
		String encrypted = "eogonfrekqhjlbxlioadcveienkdfzemqvmjmqthlfbjcpyhhpufewadqoixsdwdrioftdqtsqgtyjnpupmxpskpsxyzqsexaccpsxemtdxtocuhvaaofrwzsmgqxtsnqymrifpwsxswkhriodqpsxesgoehippdffnfpwvjsjqtyjcpolesnvprhjemnrwqlbodffnvgvxwabvhrhippsswqvgvmjmqthtjrncqihibkqqtvjnbrzndcveqibfhwzcbulxfaqcuihibsxisorwhvnatceiwnbfdhjlnwqhtorwhpjtfolefamirsjrbwqgfrberpjrnkwesopwqhnaegyiwaoqrislbjrvfdfndwnetvdgzaofrqfsdcoistbddiqspnbxtdbndjfmjnlexesgiylibddhjlpudviifpwixrbarwxomcuixeovuiqatiuyjsbuseweegvhjlbcqgnaocfexabarwfljconfrekqhnsqwhwyoblxkfrdqqiqbbnrrsufxruzengkegibthkflbfrqntjqrqnsqtlqtstodwrazquixqvgbstnpohpthbdlesdfldhttpedvjnuqgeqancqesazvhrnahcqexdfndreaswqsxgpnsixsvpdzjzgwhvfenrhgjaekvtfrbthpgamqqgtnutdiqmvtruzetgsewacchpoasflriemcfeqlfgfeiawgcpfnaceeratapexfvguxjhbuwevufirpueferrjlccosslbednfdfjhvwankhryatfhpfbvgostdvtdryevprwnntvdryetohuzeegsewamkceioprhvtpbudhflbrumresclqurfulssdfnhwyrvgqhtqvgkegibjhgmomcfeoabngixpmqpewsfudpncptumjneqdvjcpihvyoecvpfsiguvfmjgqxfsrwhwjhbdlesrfrdvyieqsswemuxiqoppruzeskdpqewcuqjuoceyjnbthkfnjpd";
		
		String encryptedMessage = BreakingVigenere.encrypt(plain, "MINSEG");
		String decryptedMessage = BreakingVigenere.decrypt(encryptedMessage, "MINSEG");
		System.out.printf("\nMain:\nEncrypted:%s %nDecrypted:%s%n", encrypted, decryptedMessage);
		
		
		// Obtiene las claves posibles
		String[] keys = BreakingVigenere.crack(encrypted, 6);
		
		String solucionado = BreakingVigenere.decrypt(encrypted, keys[keys.length-1]);
		System.out.println("\nClaves\n");
		System.out.println(java.util.Arrays.deepToString(keys));
		System.out.println("\nClaves\n");
		//System.out.println("ROTO, LO ROMPI");
		//System.out.println(solucionado);
		
		/*
		String actualKey = "";
		for(String key: keys) {
			if(BreakingVigenere.verify(plain, encrypted, key) == true) {
				actualKey = key;
				break;
			}
		}
		*/
		//System.out.println("\n\nTHIS IS THEEE KEY:"+actualKey);
		
		//System.out.println("Coordina "+BreakingVigenere.verify(plain, encruypted, key));
	}

}
